version: '2'
services:
  gamma-app:
    image: 0.0.0.0:5000/user-function
    command: node /code/app.js
    ports: 
      - "8000:8000"
    depends_on:
      - node

  node:
    image: node:7.2
    depends_on:
      - ubuntu

  ubuntu:
    image: ubuntu 
